### ISSUE TITLE
simplify

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/export-files#2]
This is too bloated atm. I'm going to need to either remove functionality or look at lazy loading modules to reduce init time. 

currently it takes about 45 ms just to load the module, before the module even has a chance to do it's thing. 

ping @tunnckoCore since you also use this and had some ideas about this before. I'm now thinking that this should not have any options at all and I can create a different project to do the other stuff we added to this. sound okay?

**Comment by tunnckoCore** [comment]
Sounds strange, but okey. You already made the things :+1:

**Comment by jonschlinkert** [comment]
Yeah, I did some basic benchmarks and with only one file, export-files took 70ms to load!  Now it takes 10ms to load a directory of files. If you add that up, it's probably the main reason that verb takes 1 second to load.  It had to be changed, sorry I did it before your feedback

**Comment by tunnckoCore** [comment]
Haha, no problem. And no, I bet it isn't main reason. :D Main reason is glob->glob-stream->vfs and through2

**Comment by jonschlinkert** [comment]
> Main reason is glob->glob-stream->vfs

maybe. I'm trying to make it faster, but verb is always going to take a while to load since it has to build up a context from the user's environment. It is what it is :)

**Comment by jonschlinkert** [comment]
you're right about vfs

![image](https://cloud.githubusercontent.com/assets/383994/6712537/72d01ba8-cd63-11e4-8cc9-6291dec5d600.png)

`lib/stack` has to load vfs, so that number is inflated by vfs

For a module that does so little it has a huge footprint. By comparison, Template has like 50 methods.

**Comment by tunnckoCore** [comment]
Yep. Hm, what are you using for this benchmarks? Looks really great!

**Comment by tunnckoCore** [comment]
I sure that one day we'll replace vinyl(-fs) core - glob/glob-stream, which is the main reason for this performance leaks.

**Comment by jonschlinkert** [comment]
> what are you using for this benchmarks? Looks really great!

thanks, that was just a table from this: https://github.com/jonschlinkert/time-require. 

the benchmarks were just two directories, like what's in [here](https://github.com/jonschlinkert/export-files/tree/master/fixtures/nested), with one using export-files and the other explicitly defined require statements. I didn't want to commit them and also just realized I forgot to remove the fixtures :)

**Comment by jonschlinkert** [comment]
> replace vinyl(-fs) core - glob/glob-stream

perhaps. I use all of these things on my own projects, and I really have a lot of fun working on the globbing stuff, so hopefully it benefits others
