### ISSUE TITLE
support export json..

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/export-files#3]
doh.. LOL!
there's nothing problem to export also JSON files, because require works for them. 
Won't hit performance, Im sure. 

I don't want to use `to-exports` or etc, exactly for performance reasons.

**Comment by tunnckoCore** [comment]
just https://github.com/jonschlinkert/export-files/blob/master/index.js#L32-L35

**Comment by tunnckoCore** [comment]
``` js
function isValid(fp) {
  return fp.indexOf('index.js') === -1
    && (fp.substr(-3) === '.js' || fp.substr(-5) === '.json');
}

function basename(fp) {
  return fp.substr(0, fp.length - path.extname(fp).length);
}
```

works for me

**Comment by jonschlinkert** [comment]
> export also JSON files, because require works for them.

it does, but only if the contents of the JSON file will never change during the lifetime of the requires cache. This is okay for things like `package.json`, but if you're loading JSON files in a directory that they might be data files, and if you use `watch` or something then the changes won't be loaded.

**Comment by tunnckoCore** [comment]
hm, thx, didn't know that.

nope, will use it for static json files

**Comment by jonschlinkert** [comment]
K, but this still is probably not a good fit for this lib since a lot of users would use it for non-static json files (like me, with verb, assemble, template, etc). hmm, then again, the problem goes away if we just use `JSON.parse(fs.readFileSync(fp))`. let me think about it

**Comment by tunnckoCore** [comment]
yea, or just `azer/read-json`
hmm

**Comment by tunnckoCore** [comment]
@jonschlinkert hm.. or we can create `export-data-files` which will be also so simple but reading just only yaml and json files? Because in a bit i'll PR to [jonschlinkert/read-data](https://github.com/tunnckoCore/read-data)

**Comment by doowb** [comment]
I view this lib as being used by someone inside their own lib. If that is the case, then I think you should allow a whitelist of extensions and default it to `'.js'` maybe `['.js', '.json']`. But this will allow using `export-files` when other extensions are registered with `require`:

``` js
module.exports = exportFiles(__dirname, ['.js', '.coffee', '.jsx', '.6to5', '.jonschlinkert']);
```

I know that last one will happen sometime :grinning:

**Comment by jonschlinkert** [comment]
lol. then we definitely need to stop this madness. I don't want to support anything beyond `.js` and maybe reading `.json` files (versus requiring). but the others require additional dependencies, which I'm kind of against for this. I'm not completely against it, but it's a slippery slope

**Comment by doowb** [comment]
I just realized that when someone wants to use `.coffee` or `.jsx`, those extensions are registered with `require` so you can just find the extensions and use those as the whitelist. This doesn't require any additional dependencies in `export-files`, it's just supporting whatever `require` would already support.

**Comment by jonschlinkert** [comment]
> It's just supporting whatever require would already support.

But I was just saying in [this comment](https://github.com/jonschlinkert/export-files/issues/3#issuecomment-87930662) that required files are cached, which makes this a bad choice if these files might be changed while being watched or something

**Comment by jonschlinkert** [comment]
or am I missing something?

**Comment by doowb** [comment]
I don't think this library should be used for loading data that's going to change in a process. Just support normal `require` functionality so it can be used for code. If you need to reload code files you'd have to clear `require.cache` anyway.

**Comment by tunnckoCore** [comment]
:+1: yep, and one notice in readme would be enough

**Comment by jonschlinkert** [comment]
> Just support normal require functionality so it can be used for code

what kind of non `.js` files (multiple) would be used that way? I can only think of cases where one file at a time would be loaded (like package.json or config files). It's hard to justify adding overhead to this for that kind of use case

**Comment by doowb** [comment]
I'm just suggesting that if you wanted to support the normal `require` functionality which allows people to register other extensions for transpilers, like `coffeescript`, `jsx`, and `ES6`, then you wouldn't want to restrict to just `.js`.

But... I see why you're doing it since you're just reading in the entire directory and basically filtering out everything that's not `.js` since those other files usually can't be `required`.

I don't see us using that functionality at the moment so it's not a big deal and probably shouldn't be added until we actually need it.

**Comment by jonschlinkert** [comment]
k, good points. when we need those other file types for a specific use case we'll get them added. closing for now
